{
 "title": "Fritz!Exporter",
 "description": "Demo Dashboard for stats from fritz_exporter (https://github.com/pdreker/fritzbox_exporter)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(fritz_update_available, friendly_name)"
   },
   {
    "name": "wifi",
    "label": "WiFi Network",
    "query": "label_values(fritz_wifi_status, wifi_name)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "DSL Link Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wan_phys_link_status{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "DSL Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_status{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "PPP Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_ppp_connection_state{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "PPP Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_ppp_connection_uptime_seconds_total{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "DSL Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_status_enabled{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "LAN Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_lan_status{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "LAN Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_lan_status_enabled{friendly_name=~\"$device\"}"
    }
   ]
  },
  {
   "title": "Update available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_update_available{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "Known Devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_known_devices_count{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(fritz_uptime_seconds_total{friendly_name=\"$device\"}) without(softwareversion)"
    }
   ]
  },
  { "title": "LAN", "type": "row", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 } },
  {
   "title": "LAN bytes/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(fritz_lan_data_bytes_total{friendly_name=\"$device\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "LAN packet/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "irate(fritz_lan_packet_count_total{friendly_name=\"$device\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  { "title": "Wifi", "type": "row", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 } },
  {
   "title": "Wifi Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{friendly_name=~\"$device\", wifi_name=\"$wifi\"}",
     "legendFormat": "{{ enabled }}"
    }
   ]
  },
  {
   "title": "SSID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{friendly_name=~\"$device\", wifi_name=\"$wifi\"}",
     "legendFormat": "{{ ssid }}"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_channel{friendly_name=~\"$device\", wifi_name=\"$wifi\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{friendly_name=~\"$device\", wifi_name=\"$wifi\"}"
    }
   ]
  },
  {
   "title": "Associations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_associations_count{friendly_name=~\"$device\", wifi_name=\"$wifi\"}"
    }
   ]
  },
  {
   "title": "Wifi standard",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{friendly_name=~\"$device\", wifi_name=\"$wifi\"}",
     "legendFormat": "802.11{{ standard }}"
    }
   ]
  },
  {
   "title": "Packets/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "irate(fritz_wifi_packets_count_total{friendly_name=\"$device\", wifi_name=\"$wifi\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Associations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "fritz_wifi_associations_count{friendly_name=\"$device\", wifi_name=\"$wifi\"}",
     "legendFormat": "associations"
    }
   ]
  },
  { "title": "WAN", "type": "row", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 } },
  {
   "title": "WAN bytes/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(fritz_wan_data_bytes_total{friendly_name=\"$device\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "WAN packet/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "irate(fritz_wan_data_packets_count_total{friendly_name=\"$device\"}[10m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  { "title": "DSL Link", "type": "row", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 } },
  {
   "title": "Current linkrate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_datarate_kbps{type=\"curr\", friendly_name=\"$device\"}",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Max linkrate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_datarate_kbps{type=\"max\", friendly_name=\"$device\"}",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "DSL attenuation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_attenuation_dB{friendly_name=\"$device\"}",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "DSL noise margin",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_noise_margin_dB{friendly_name=\"$device\"}",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "DSL Error Rates",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "rate(fritz_dsl_crc_errors_count_total{friendly_name=\"$device\"}[10m])",
     "legendFormat": "FEC"
    },
    {
     "expr": "rate(fritz_dsl_fec_errors_count_total{friendly_name=\"$device\"}[10m])",
     "legendFormat": "CRC"
    }
   ]
  }
 ]
}