name: Check PR labels

on:
  pull_request:
    branches:
      - master
    types: ["opened", "synchronize", "labeled", "unlabeled"]

jobs:
  check-label:
    name: Check PR labelling
    runs-on: ubuntu-latest
    outputs:
      pr_tags_present: ${{ steps.pr_label_check.outputs.label_check }}
    steps:
      - uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "patch, minor, major"
